config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'committees/index'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  resources :people do
    collection do
      get 'export', to: 'people#export', as: 'export'
    end
    resources :updates do
      member do
        get :add_tags
        patch :update_tags
      end
    end
    member do
      get 'edit_notes'
      patch 'update_notes'
    end
  end

  get 'refresh_permissions', to: 'users#refresh_permissions'
  get 'permissions', to: 'static_pages#permissions'
  resources :user_permissions, only: [] do
    member do
      patch :toggle
    end
  end
  resources :bugs
  resources :users, only: [:index] do
    member do
      patch :make_admin
      patch :make_permitted
      patch :revoke_permissions
    end
  end
  resources :regions, only: [:index, :show]
  resources :committees, only: [:index, :show]
  resources :tags
  get 'all_updates', to: 'updates#all_updates'
  get '/tags/search', to: 'tags#search'

  root "people#index"
end

app/models/person.rb
class Person < ApplicationRecord
  attr_accessor :creating_user_id
  enum party: { Conservative: 0, Labour: 1, liberalDemocrats: 2, snp: 3, other: 4 }
  has_many :updates, dependent: :destroy
  has_many :committee_memberships, dependent: :destroy
  has_many :committees, through: :committee_memberships
  has_many :government_posts, dependent: :destroy
  belongs_to :region, optional: true

  # Removed belongs_to :user association
  # Removed attr_accessor :author_id as it's no longer needed

  # validates :member_id, presence: true, uniqueness: true
  # validates :active_status, inclusion: { in: [true, false] }

  after_create :create_initial_update

  def active_membership?
    active_status && (membership_end_date.nil? || membership_end_date.future?)
  end

  def last_name
    # This will split the name by spaces and return the last element.
    # It's a simplistic approach and might need adjustment for edge cases.
    name.split(' ').last
  end

  private

  def create_initial_update
    updates.create(content: "Automatic Update ** Person created **", user_id: creating_user_id)
  end
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :person
  belongs_to :user

  has_many :taggings, foreign_key: 'related_update_id', dependent: :destroy
  has_many :tags, through: :taggings
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!

  def edit_notes
    @person = Person.find(params[:id])
  end

  def update_notes
    @person = Person.find(params[:id])
    if @person.update(notes_params)
      redirect_to @person, notice: 'Notes were successfully updated.'
    else
      render :edit_notes
    end
  end

  def index
    @people = Person.all.includes(:updates)

    apply_filters = false

    if params[:region_ids].present? && params[:region_ids].reject(&:empty?).any?
      @people = @people.where(region_id: params[:region_ids].reject(&:empty?))
      apply_filters = true
    end

    if params[:search].present? && params[:search].strip != ''
      @people = @people.where("LOWER(name) LIKE ? OR LOWER(constituency) LIKE ?", "%#{params[:search].strip.downcase}%", "%#{params[:search].strip.downcase}%")
      apply_filters = true
    end

    if params[:majority_min].present?
      @people = @people.where('majority >= ?', params[:majority_min])
      apply_filters = true
    end

    if params[:majority_max].present?
      @people = @people.where('majority <= ?', params[:majority_max])
      apply_filters = true
    end

    if params[:start_date].present?
      @people = @people.where('membership_start_date >= ?', params[:start_date])
      apply_filters = true
    end

    if params[:end_date].present?
      @people = @people.where('membership_start_date <= ?', params[:end_date])
      apply_filters = true
    end

    if params[:sort].present? && params[:sort].strip != ''
      case params[:sort]
      when 'majority_asc'
        @people = @people.order(majority: :asc)
      when 'majority_desc'
        @people = @people.order(majority: :desc)
      when 'area_asc'
        @people = @people.order(area: :asc)
      when 'area_desc'
        @people = @people.order(area: :desc)
      when 'membership_start_asc'
        @people = @people.order(membership_start_date: :asc)
      when 'membership_start_desc'
        @people = @people.order(membership_start_date: :desc)
      when 'name_asc'
        @people = @people.order('name ASC')
      when 'name_desc'
        @people = @people.order('name DESC')
      when 'constituency_asc'
        @people = @people.order(constituency: :asc)
      when 'constituency_desc'
        @people = @people.order(constituency: :desc)
      end
      apply_filters = true
    end

    if params[:tag_ids].present? && params[:tag_ids].reject(&:empty?).any?
      tagged_update_ids = Tagging.where(tag_id: params[:tag_ids].reject(&:empty?)).pluck(:related_update_id)
      tagged_person_ids = Update.where(id: tagged_update_ids).pluck(:person_id).uniq
      @people = @people.where(id: tagged_person_ids)
      apply_filters = true
    end

    unless apply_filters
      @people = @people.sort_by { |person| person.name.split.last.downcase }
      # Convert array to a paginatable collection
      @people = Kaminari.paginate_array(@people).page(params[:page]).per(25)
    else
      # Apply pagination normally when @people is an ActiveRecord::Relation
      @people = @people.page(params[:page]).per(25)
    end

    @area_rankings = Person.order(area: :desc).pluck(:area).uniq
    @area_ranks = @people.map { |p| @area_rankings.index(p.area) + 1 if p.area.present? }
  end


  def export
    @people = apply_filters(Person.all.includes(:updates))

    respond_to do |format|
      format.xlsx do
        response.headers['Content-Disposition'] = "attachment; filename=People_#{Time.now.strftime('%Y%m%d%H%M%S')}.xlsx"
      end
    end
  end


  def show
    @person = Person.find(params[:id])
    @current_committees = @person.committee_memberships.where(end_date: nil)
    .select { |membership| !membership.committee.name.downcase.include?('bill') }
    @past_committees = @person.committee_memberships.where.not(end_date: nil)

    constituency_name = @person.constituency
    constituency_search_url = "https://members-api.parliament.uk/api/Location/Constituency/Search?searchText=#{constituency_name}&skip=0&take=20"
    search_response = HTTParty.get(constituency_search_url)
    if search_response.success? && search_response.parsed_response["items"].any?
      constituency_id = search_response.parsed_response["items"].first["value"]["id"]
      geometry_url = "https://members-api.parliament.uk/api/Location/Constituency/#{constituency_id}/Geometry"
      geometry_response = HTTParty.get(geometry_url)
      if geometry_response.success?
        @constituency_geometry = geometry_response.parsed_response["value"]
      end
    end

    ranked_areas = Person.order(area: :desc).pluck(:id, :area).map(&:last)
    @area_rank = ranked_areas.index(@person.area) + 1 if @person.area

    if geometry_response.success?
      geometry_data = JSON.parse(geometry_response.parsed_response["value"])
      # Assuming the geometry is a polygon and you want the first set of coordinates
      @constituency_coordinates = geometry_data["coordinates"].first
    end
    uk_location = Geocoder.search("United Kingdom").first
    @uk_coordinates = [uk_location.longitude, uk_location.latitude] if uk_location
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.creating_user_id = current_user.id

    if @person.save
      redirect_to @person, status: :see_other, notice: 'Person was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person, status: :see_other, notice: 'Person was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully deleted.'
  end

  private

  def notes_params
    params.require(:person).permit(:notes)
  end

  def person_params
    params.require(:person).permit(:name, :party, :role, :notes, :region_id)
  end

  def apply_filters(scope)
    if params[:region_ids].present? && params[:region_ids].reject(&:empty?).any?
      scope = scope.where(region_id: params[:region_ids].reject(&:empty?))
    end

    if params[:search].present? && params[:search].strip != ''
      scope = scope.where("name LIKE ? OR constituency LIKE ?", "%#{params[:search].strip}%", "%#{params[:search].strip}%")
    end

    if params[:majority_min].present?
      scope = scope.where('majority >= ?', params[:majority_min])
    end

    if params[:majority_max].present?
      scope = scope.where('majority <= ?', params[:majority_max])
    end

    if params[:start_date].present?
      scope = scope.where('membership_start_date >= ?', params[:start_date])
    end

    if params[:end_date].present?
      scope = scope.where('membership_start_date <= ?', params[:end_date])
    end

    if params[:sort].present? && params[:sort].strip != ''
      case params[:sort]
      when 'majority_asc'
        scope = scope.order(majority: :asc)
      when 'majority_desc'
        scope = scope.order(majority: :desc)
      when 'area_asc'
        scope = scope.order(area: :asc)
      when 'area_desc'
        scope = scope.order(area: :desc)
      when 'membership_start_asc'
        scope = scope.order(membership_start_date: :asc)
      when 'membership_start_desc'
        scope = scope.order(membership_start_date: :desc)
      when 'name_asc'
        scope = scope.sort_by { |person| person.name.split.last.downcase }
      when 'name_desc'
        scope = scope.sort_by { |person| person.name.split.last.downcase }.reverse
      when 'constituency_asc'
        scope = scope.order(constituency: :asc)
      when 'constituency_desc'
        scope = scope.order(constituency: :desc)
      end
    end

    if params[:tag_ids].present? && params[:tag_ids].reject(&:empty?).any?
      tagged_update_ids = Tagging.where(tag_id: params[:tag_ids].reject(&:empty?)).pluck(:related_update_id)
      tagged_person_ids = Update.where(id: tagged_update_ids).pluck(:person_id).uniq
      scope = scope.where(id: tagged_person_ids)
    end

    scope
  end


  # def sort_column
  #   # Since user_id is no longer a column, remove it from the sort options.
  #   %w[name party constituency created_at updated_at].include?(params[:sort]) ? params[:sort] : 'created_at'
  # end

  # def sort_direction
  #   %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  # end

  # def next_direction(column)
  #   column == params[:sort] && params[:direction] == 'asc' ? 'desc' : 'asc'
  # end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
    <%= form_with(model: person, local: true, class: "needs-validation", novalidate: "") do |form| %>
      <% if person.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>
          <ul>
            <% person.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group my-2">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, id: :person_name, class: 'form-control' %>
      </div>

      <div class="form-group mb-2">
        <%= form.label :party, class: 'form-label' %>
        <%= form.select :party, Person.parties.keys.map { |party| [party.titleize, party] }, { include_blank: true }, { id: :person_party, class: 'form-select' } %>
      </div>

      <div class="form-group mb-2">
        <%= form.label :role, class: 'form-label' %>
        <%= form.text_field :role, id: :person_role, class: 'form-control' %>
      </div>

      <div class="form-group mb-2">
        <%= form.label :region_id, class: 'form-label' %>
        <%= form.collection_select :region_id, Region.order(:name), :id, :name, { include_blank: true }, { id: :person_region_id, class: 'form-select' } %>
      </div>


      <div class="form-group mb-2">
        <%= form.label :notes, class: 'form-label' %>
        <%= form.text_area :notes, id: :person_notes, class: 'form-control' %>
      </div>

      <div class="actions mb-2">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    <% end %>

app/views/people/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="mb-4">Edit Person</h1>

      <%= render 'form', person: @person %>

      <%= link_to 'Back', people_path %>
    </div>
  </div>
</div>

app/views/people/edit_notes.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="mb-3">Edit Notes for <%= @person.name %></h1>

      <%= form_with(model: @person, url: update_notes_person_path(@person), method: :patch, local: true, class: "needs-validation", novalidate: "") do |form| %>
        <div class="mb-3">
          <%= form.label :notes, class: 'form-label' %>
          <%= form.text_area :notes, class: 'form-control', rows: 6 %>
        </div>

        <div class="actions">
          <%= form.submit "Save Notes", class: 'btn btn-primary' %>
        </div>
      <% end %>

      <%= link_to 'Back', @person, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="mb-4">New Person</h1>

      <%= render 'form', person: @person %>

      <%= link_to 'Back', people_path %>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class="container mt-3">
  <h1 class="card-title"><%= @person.name %></h1>
  <br>
  <div class="card">
    <div class="card-body">
      <div class="row mb-3">
        <div class="col-md-4 d-flex align-items-center justify-content-center ">
          <% if @person.portrait_url.present? %>
            <img src="<%= @person.portrait_url %>" alt="<%= @person.name %>'s portrait" style="max-width: 160px; height: auto; border-radius: 15px;" class="mb-3">
          <% end %>
        </div>
        <div class="col-md-4">
          <% if @person.government_posts.where(end_date: nil).any? %>
            <p class="card-text"><strong>Current Government Roles:</strong>
              <% @person.government_posts.where(end_date: nil).each_with_index do |post, index| %>
                <%= post.name %><%= ',' unless index == @person.government_posts.where(end_date: nil).count - 1 %>
              <% end %>
            </p>
          <% end %>
          <p class="card-text"><strong>Member id:</strong> <%= @person.member_id %></p>
          <% if @person.region && @person.region.name.present? %>
            <p class="card-text"><strong>Region:</strong>
              <%= link_to @person.region.name, region_path(@person.region) %>
            </p>
          <% else %>
            <p class="card-text"><strong>Region:</strong> N/A</p>
          <% end %>
          <p class="card-text"><strong>Majority:</strong> <%= @person.majority %></p>
          <p class="card-text"><strong>Area Rank:</strong> <%= @area_rank %> out of <%= Person.count %></p>
          <p class="card-text mb-3"><strong>Constituency:</strong> <%= @person.constituency %></p>
        </div>
        <div class="col-md-4">
          <p class="card-text"><strong>Status:</strong> <%= @person.active_status ? 'Active' : 'Not Active' %></p>
          <p class="card-text"><strong>Installed:</strong> <%= formatted_update_time(@person.membership_start_date) %></p>
          <% if @person.membership_end_date %>
            <p class="card-text"><strong>End Time:</strong> <%= formatted_update_time(@person.membership_end_date) %></p>
          <% end %>
          <p class="card-text">
            <strong>Email:</strong>
            <a href="mailto:<%= @person.email %>"><%= @person.email %></a>
          </p>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-12 d-flex align-items-center">
          <h5 class="mb-0">Notes:</h5>
          <%= link_to 'Edit Notes', edit_notes_person_path(@person), class: 'btn btn-secondary btn-sm ms-2' %>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-12">
          <div class="alert alert-info" role="alert">
            <p class="mb-0"><%= @person.notes.presence || 'Click Edit Notes to add Notes' %></p>
          </div>
        </div>
      </div>
      <h5>Associated Tags</h5>
      <div id="update-tags" class="mb-3">
        <% unique_tags = @person.updates.flat_map(&:tags).uniq %>
        <h5><% unique_tags.each do |tag| %>
          <%= link_to tag_path(tag), class: "tag-badge" do %>
            <span class="badge bg-primary"><%= tag.name %></span>
          <% end %>
        <% end %></h5>
        <% if unique_tags.empty? %>
          <p>No associated tags.</p>
        <% end %>
      </div>

      <div class="row mt-3">
        <div class="col-12 d-flex align-items-center">
          <h5>Most Recent Updates</h5>
          <%= link_to 'See Updates', person_updates_path(@person), class: 'btn btn-primary btn-sm mx-2 mb-2' %>
          <%= link_to 'New Update', new_person_update_path(@person), class: 'btn btn-success btn-sm mb-2' %>
        </div>
        <% @person.updates.order(created_at: :desc).limit(3).each do |update| %>
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <% if update.content == "Automatic Update ** Person created **" %>
                  <h6 class="card-subtitle mb-2 text-muted"><%= update.created_at %></h6>
                <% else %>
                  <h6 class="card-subtitle mb-2 text-muted"><%= update.comment_date %></h6>
                <% end %>
                <p class="card-text"><%= update.content %></p>
                <% if update.occasion.present? %>
                  <p class="card-text text-end">Occasion: <%= update.occasion %></p>
                <% end %>

                <!-- Tags Section -->
                <div class="update-tags mt-2">
                  <% update.tags.each do |tag| %>
                    <%= link_to tag_path(tag), class: "tag-badge" do %>
                      <span class="badge bg-secondary"><%= tag.name %></span>
                    <% end %>
                  <% end %>
                </div>

                <div class="d-flex justify-content-end mt-2">
                  <%= link_to 'Details', [update.person, update], class: 'btn btn-secondary btn-sm' %>
                  <% unless update.content == 'Automatic Update ** Person created **' %>
                    <%= link_to 'Edit', edit_person_update_path(update.person, update), class: 'btn btn-primary btn-sm mx-2' %>
                    <%= link_to 'Delete', [update.person, update], data: { turbo_method: :delete, turbo_confirm: 'Are you sure?', turbo_action: "replace", turbo_target: "person_updates_#{update.person.id}" }, class: 'btn btn-danger btn-sm' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>


      <div class="accordion" id="personDetailsAccordion">
        <% if @person.government_posts.where(end_date: nil).any? %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="currentGovernmentPostsHeader">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#currentGovernmentPosts" aria-expanded="false" aria-controls="currentGovernmentPosts">
                Current Government Posts
              </button>
            </h2>
            <div id="currentGovernmentPosts" class="accordion-collapse collapse" aria-labelledby="currentGovernmentPostsHeader" data-bs-parent="#personDetailsAccordion">
              <div class="accordion-body">
                <ul>
                  <% @person.government_posts.where(end_date: nil).each do |government_post| %>
                    <li>
                      <%= government_post.name %> (Start Date: <%= formatted_update_time(government_post.start_date) %>)
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>

        <% if @person.government_posts.where.not(end_date: nil).any? %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="pastGovernmentPostsHeader">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#pastGovernmentPosts" aria-expanded="false" aria-controls="pastGovernmentPosts">
                Past Government Posts
              </button>
            </h2>
            <div id="pastGovernmentPosts" class="accordion-collapse collapse" aria-labelledby="pastGovernmentPostsHeader" data-bs-parent="#personDetailsAccordion">
              <div class="accordion-body">
                <ul>
                  <% @person.government_posts.where.not(end_date: nil).each do |government_post| %>
                    <li>
                      <%= government_post.name %> (Start Date: <%= formatted_update_time(government_post.start_date) %>, End Date: <%= formatted_update_time(government_post.end_date) %>)
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>

        <% if @current_committees.any? %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="currentCommitteesHeader">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#currentCommittees" aria-expanded="false" aria-controls="currentCommittees">
                Current Committees
              </button>
            </h2>
            <div id="currentCommittees" class="accordion-collapse collapse" aria-labelledby="currentCommitteesHeader" data-bs-parent="#personDetailsAccordion">
              <div class="accordion-body">
                <ul>
                  <% @current_committees.each do |membership| %>
                    <li>
                      <a href="<%= committee_path(membership.committee) %>"><%= membership.committee.name %></a> (From: <%= formatted_update_time(membership.start_date) %>)
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>


      <div class="mt-3" id="mapContainer" style="">
        <div style="width: 100%; height: 300px; border-radius: 15px;"
            data-controller="map"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            data-map-uk-coordinates-value="<%= @uk_coordinates.to_json %>"
            data-map-constituency-coordinates-value="<%= @constituency_coordinates.to_json %>">
        </div>
      </div>

      <div class="mt-3">
        <%= link_to 'Edit', edit_person_path(@person), class: 'btn btn-primary mr-2 mb-2' %>
        <%= link_to 'Back', people_path, class: 'btn btn-secondary mr-2 mb-2' %>
        <%# <%= link_to 'Delete', @person, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  const constituency = "<%= @person.constituency %>";
  fetchConstituencyData(constituency);

  const toggleMapButton = document.getElementById('toggleMapButton');
  const mapContainer = document.getElementById('mapContainer');

  toggleMapButton.addEventListener('click', () => {
    if (mapContainer.style.display === 'none') {
      mapContainer.style.display = 'block';
      toggleMapButton.textContent = 'Hide Map';
    } else {
      mapContainer.style.display = 'none';
      toggleMapButton.textContent = 'Show Map';
    }
  });
});

function fetchConstituencyData(constituency) {
  fetch(`https://members-api.parliament.uk/api/Location/Constituency/Search?searchText=${constituency}&skip=0&take=20`)
    .then(response => response.json())
    .then(data => {
      const constituencyId = data.items[0].value.id;
      fetchConstituencyGeometry(constituencyId);
    });
}

function fetchConstituencyGeometry(constituencyId) {
  fetch(`https://members-api.parliament.uk/api/Location/Constituency/${constituencyId}/Geometry`)
    .then(response => response.json())
    .then(data => {
      document.getElementById('constituency-geometry').textContent = data.value;
    });
}

</script>
<style>
  .tag-badge {
    text-decoration: none; /* Removes underline */
  }

  .tag-badge .badge {
    color: white; /* Ensures text color is white */
  }
</style>