config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'committees/index'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  resources :people do
    collection do
      get 'export', to: 'people#export', as: 'export'
    end
    resources :updates do
      member do
        get :add_tags
        patch :update_tags
      end
    end
    member do
      get 'edit_notes'
      patch 'update_notes'
    end
  end

  get 'refresh_permissions', to: 'users#refresh_permissions'
  get 'permissions', to: 'static_pages#permissions'
  resources :user_permissions, only: [] do
    member do
      patch :toggle
    end
  end
  resources :bugs
  resources :users, only: [:index] do
    member do
      patch :make_admin
      patch :make_permitted
      patch :revoke_permissions
    end
  end
  resources :regions, only: [:index, :show]
  resources :committees, only: [:index, :show]
  resources :tags
  get 'all_updates', to: 'updates#all_updates'
  get '/tags/search', to: 'tags#search'

  root "people#index"
end

app/models/committee.rb
class Committee < ApplicationRecord
  has_many :committee_memberships, dependent: :destroy
  has_many :people, through: :committee_memberships
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :authenticate_user!

  def index
    @committees = Committee.where("LOWER(name) NOT LIKE '%bill%'")
    @current_committee_memberships = []
    @past_committee_memberships = []

    if params[:search].present?
      search_term = "%#{params[:search].downcase}%"
      @committees = @committees.where("LOWER(name) LIKE ?", search_term)

      @people = Person.where("LOWER(name) LIKE ?", search_term)
      @people.each do |person|
        current_memberships = person.committee_memberships.joins(:committee)
                                 .where("LOWER(committees.name) NOT LIKE '%bill%'")
                                 .where('committee_memberships.end_date IS NULL OR committee_memberships.end_date > ?', Time.now)
        @current_committee_memberships += current_memberships unless current_memberships.empty?

        past_memberships = person.committee_memberships.joins(:committee)
                              .where("LOWER(committees.name) NOT LIKE '%bill%'")
                              .where('committee_memberships.end_date <= ?', Time.now)
        @past_committee_memberships += past_memberships unless past_memberships.empty?
      end
    end
  end

  def show
    @committee = Committee.find(params[:id])
    return if @committee.name.downcase.include?('bill')

    @current_members = @committee.people.joins(:committee_memberships)
                            .where('committee_memberships.end_date IS NULL OR committee_memberships.end_date > ?', Time.now)
                            .distinct
    @past_members = @committee.people.joins(:committee_memberships)
                          .where('committee_memberships.end_date <= ?', Time.now)
                          .distinct
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/index.html.erb
<div class="container mt-3">
  <h1>All Committees</h1>

  <%= form_with url: committees_path, method: :get, local: true do |form| %>
    <div class="input-group mb-3">
      <%= link_to "Clear", committees_path, class: 'btn btn-outline-secondary' %>
      <%= form.text_field :search, value: params[:search], placeholder: "Search by committee name or person", class: "form-control", id: "searchField" %>
      <button class="btn btn-outline-primary" type="submit">Search</button>
    </div>
  <% end %>

  <% if @people.present? %>
    <% @people.each do |person| %>
      <div class="row mt-3">
        <div class="col">
          <h2><%= person.name %></h2>
        </div>
      </div>
      <div class="row">
        <% if person.committee_memberships.present? %>
          <div class="col">
            <h3>Present Committee Memberships</h3>
            <ul>
              <% person.committee_memberships.each do |membership| %>
                <% if membership.end_date.nil? || membership.end_date > Time.now %>
                  <li><%= link_to membership.committee.name, committee_path(membership.committee) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if person.committee_memberships.present? %>
          <div class="col">
            <h3>Past Committee Memberships</h3>
            <ul>
              <% person.committee_memberships.each do |membership| %>
                <% if membership.end_date.present? && membership.end_date <= Time.now %>
                  <li><%= link_to membership.committee.name, committee_path(membership.committee) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <% if @committees.present? %>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @committees.each do |committee| %>
          <tr>
            <td><%= link_to committee.name, committee_path(committee) %></td>
            <td>
              <%= link_to 'Show', committee_path(committee), class: 'btn btn-primary' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/committees/show.html.erb
<div class="container mt-3">
  <h1><%= @committee.name %></h1>

  <div class="accordion" id="committeeMembersAccordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="currentMembersHeader">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#currentMembers" aria-expanded="true" aria-controls="currentMembers">
          Current Members
        </button>
      </h2>
      <div id="currentMembers" class="accordion-collapse collapse show" aria-labelledby="currentMembersHeader" data-bs-parent="#committeeMembersAccordion">
        <div class="accordion-body">
          <ul class="list-group list-group-flush">
            <% @current_members.each do |member| %>
              <li class="list-group-item">
                <%= link_to member.name, person_path(member) %>
                <% member.committee_memberships.where(committee: @committee).each do |membership| %>
                  (Joined: <%= formatted_update_time(membership.start_date) %>)
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header" id="pastMembersHeader">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#pastMembers" aria-expanded="false" aria-controls="pastMembers">
          Past Members
        </button>
      </h2>
      <div id="pastMembers" class="accordion-collapse collapse" aria-labelledby="pastMembersHeader" data-bs-parent="#committeeMembersAccordion">
        <div class="accordion-body">
          <ul class="list-group list-group-flush">
            <% @past_members.each do |member| %>
              <li class="list-group-item">
                <%= link_to member.name, person_path(member) %>
                <% member.committee_memberships.where(committee: @committee).each do |membership| %>
                  (From: <%= formatted_update_time(membership.start_date) %> To: <%= membership.end_date ? formatted_update_time(membership.end_date) : 'Present' %>)
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Back to Committees', committees_path, class: 'btn btn-link' %>
</div>