config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'committees/index'
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  resources :people do
    collection do
      get 'export', to: 'people#export', as: 'export'
    end
    resources :updates do
      member do
        get :add_tags
        patch :update_tags
      end
    end
    member do
      get 'edit_notes'
      patch 'update_notes'
    end
  end

  get 'refresh_permissions', to: 'users#refresh_permissions'
  get 'permissions', to: 'static_pages#permissions'
  resources :user_permissions, only: [] do
    member do
      patch :toggle
    end
  end
  resources :bugs
  resources :users, only: [:index] do
    member do
      patch :make_admin
      patch :make_permitted
      patch :revoke_permissions
    end
  end
  resources :regions, only: [:index, :show]
  resources :committees, only: [:index, :show]
  resources :tags
  get 'all_updates', to: 'updates#all_updates'
  get '/tags/search', to: 'tags#search'

  root "people#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :user
end

app/models/committee.rb
class Committee < ApplicationRecord
  has_many :committee_memberships, dependent: :destroy
  has_many :people, through: :committee_memberships
end

app/models/government_post.rb
class GovernmentPost < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  attr_accessor :creating_user_id
  enum party: { Conservative: 0, Labour: 1, liberalDemocrats: 2, snp: 3, other: 4 }
  has_many :updates, dependent: :destroy
  has_many :committee_memberships, dependent: :destroy
  has_many :committees, through: :committee_memberships
  has_many :government_posts, dependent: :destroy
  belongs_to :region, optional: true

  # Removed belongs_to :user association
  # Removed attr_accessor :author_id as it's no longer needed

  # validates :member_id, presence: true, uniqueness: true
  # validates :active_status, inclusion: { in: [true, false] }

  after_create :create_initial_update

  def active_membership?
    active_status && (membership_end_date.nil? || membership_end_date.future?)
  end

  def last_name
    # This will split the name by spaces and return the last element.
    # It's a simplistic approach and might need adjustment for edge cases.
    name.split(' ').last
  end

  private

  def create_initial_update
    updates.create(content: "Automatic Update ** Person created **", user_id: creating_user_id)
  end
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :people
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :updates, through: :taggings, source: :related_update

  validates :name, uniqueness: { case_sensitive: false }

  before_destroy :check_for_updates

  private

  def check_for_updates
    if updates.any?
      errors.add(:base, 'Cannot delete tag because it has one or more updates.')
      throw(:abort)
    end
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :related_update, class_name: 'Update'
  belongs_to :tag
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :person
  belongs_to :user

  has_many :taggings, foreign_key: 'related_update_id', dependent: :destroy
  has_many :tags, through: :taggings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :updates
  has_many :bugs, dependent: :destroy

  enum role: { user: 0, permitted: 1, admin: 2 }

  private
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_permissions, only: [:index]

  def index
    @bugs = Bug.all
  end

  def show
  end

  def new
    @bug = Bug.new
  end

  def edit
  end

  def create
    @bug = Bug.new(bug_params)
    @bug.user = current_user

    if @bug.save
      redirect_to @bug, notice: 'Bug was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bug.update(bug_params)
      redirect_to @bug, notice: 'Bug was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bug.destroy
    redirect_to bugs_url, notice: 'Bug was successfully deleted.'
  end

  private

    def set_bug
      @bug = Bug.find(params[:id])
    end

    def bug_params
      params.require(:bug).permit(:title, :description)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # app/controllers/tags_controller.rb
  def show
    @tag = Tag.find(params[:id])
    # This will group updates by person, assuming you have a person association in your update model
    @updates_by_person = @tag.updates.includes(:person).group_by(&:person)
  end


  # POST /tags
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      render json: @tag, status: :created
    else
      render json: @tag.errors, status: :unprocessable_entity
    end
  end

  # GET /tags/:id/edit
  def edit
  end

  # PATCH/PUT /tags/:id
  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/:id
  def destroy
    if @tag.destroy
      redirect_to tags_path, notice: 'Tag was successfully deleted.'
    else
      redirect_to tags_path, alert: @tag.errors.full_messages.to_sentence
    end
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_update_time(updated_at)
    if updated_at > 24.hours.ago
      # For updates within the last 24 hours, show how many hours/minutes ago
      "#{time_ago_in_words(updated_at)} ago"
    else
      # For older updates, show the date
      updated_at.strftime("%d/%m/%y")
    end
  end

  def next_direction(current_column)
    if params[:sort] == current_column && params[:direction] == "asc"
      "desc"
    else
      "asc"
    end
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'ParlAssist', root_path, class: 'navbar-brand ms-5' %>
    <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-4">
        <li class="nav-item">
          <%= link_to 'People', people_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'All Updates', all_updates_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'All Committees', committees_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'All Tags', tags_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'User Management', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'All Regions', regions_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bugs', bugs_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav mx-4">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
            <li>
              <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
<% else %>
  <div class="text-center">
    <h1>ParlAssist</h1>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParlAssist</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= javascript_importmap_tags %>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
</head>

<body>
  <% if user_signed_in? && (current_user.permitted? || current_user.admin?) %>
    <%= render 'layouts/navbar' %> <!-- Render navbar only if user has permissions -->
  <% end %>
  <%= yield %>
  <div class="container mt-3">
    <% if notice %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>